FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Set environment variables with build arguments
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

ARG MONGO_PROD_DB
ENV MONGO_PROD_DB=$MONGO_PROD_DB

ARG MONGO_DEV_DB
ENV MONGO_DEV_DB=$MONGO_DEV_DB

ARG ADMIN_EMAIL
ENV ADMIN_EMAIL=$ADMIN_EMAIL

ARG ADMIN_PASS
ENV ADMIN_PASS=$ADMIN_PASS

ARG COORDINATOR_EMAIL
ENV COORDINATOR_EMAIL=$COORDINATOR_EMAIL

ARG COORDINATOR_PASS
ENV COORDINATOR_PASS=$COORDINATOR_PASS

COPY . .
RUN npm run build
RUN npm prune --production

EXPOSE 4000
CMD ["node", "dist/index.js"]
